DROP TABLE IF EXISTS TB_HEROES;
CREATE TABLE TB_HEROES (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    NOME TEXT NOT NULL,
    PODER TEXT NOT NULL
);

-- CREATE
INSERT INTO TB_HEROES (NOME, PODER)
VALUES
    ('Flash', 'Velocidade'),
    ('Aquaman', 'Falar com os animais'),
    ('Batman', 'Dinheiro');

-- READ
SELECT ID, NOME, PODER FROM TB_HEROES;
SELECT ID, NOME, PODER FROM TB_HEROES WHERE NOME = 'Flash';

-- UPDATE
UPDATE TB_HEROES
SET NOME = 'Goku', PODER = 'Deus'
WHERE ID = 1;

-- DELETE
DELETE FROM TB_HEROES WHERE ID = 2;